files:
  - source: /locale/*_en-us.json
    translation: /locale/%file_name%%locale_with_underscore%.json
    translation_replace:
      en-us: ''
  - source: /locale_steam/*_en-us.json
    translation: /locale_steam/%file_name%%locale_with_underscore%.json
    translation_replace:
      en-us: ''
  - source: /locale_store/store_en-us.csv
    translation: /locale_store/store_%locale_with_underscore%.csv
    scheme: 'identifier,source_or_translation'
  - source: /locale_store/dlc_en-us.csv
    translation: /locale_store/dlc_%locale_with_underscore%.csv
    scheme: 'identifier,source_or_translation'
  - source: /locale_store/android_news.txt
    translation: /locale_store/android_news_%locale_with_underscore%.txt
